[2021-01-29 16:51:26,279] {scheduler_job.py:154} INFO - Started process (PID=17358) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 16:51:26,318] {logging_mixin.py:112} INFO - [2021-01-29 16:51:26,317] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-29 16:51:26,319] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-29 16:51:26,319] {logging_mixin.py:112} INFO - [2021-01-29 16:51:26,319] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 16:51:26,324] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-29 16:51:26,330] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-29 16:51:26,333] {logging_mixin.py:112} INFO - [2021-01-29 16:51:26,331] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-29 16:51:26,333] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 16:51:26,345] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.067 seconds
[2021-01-29 18:11:53,850] {scheduler_job.py:154} INFO - Started process (PID=17469) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 18:11:53,937] {logging_mixin.py:112} INFO - [2021-01-29 18:11:53,935] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-29 18:11:53,940] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-29 18:11:53,941] {logging_mixin.py:112} INFO - [2021-01-29 18:11:53,941] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 18:11:53,980] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-29 18:11:54,001] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-29 18:11:54,011] {logging_mixin.py:112} INFO - [2021-01-29 18:11:54,004] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-29 18:11:54,011] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 18:11:54,037] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.187 seconds
[2021-01-29 18:42:59,227] {scheduler_job.py:154} INFO - Started process (PID=17553) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 18:42:59,268] {logging_mixin.py:112} INFO - [2021-01-29 18:42:59,267] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-29 18:42:59,269] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-29 18:42:59,269] {logging_mixin.py:112} INFO - [2021-01-29 18:42:59,269] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 18:42:59,273] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-29 18:42:59,283] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-29 18:42:59,285] {logging_mixin.py:112} INFO - [2021-01-29 18:42:59,284] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-29 18:42:59,286] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 18:42:59,296] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.069 seconds
[2021-01-29 19:12:34,586] {scheduler_job.py:154} INFO - Started process (PID=17639) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 19:12:34,751] {logging_mixin.py:112} INFO - [2021-01-29 19:12:34,748] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-29 19:12:34,763] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-29 19:12:34,766] {logging_mixin.py:112} INFO - [2021-01-29 19:12:34,765] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 19:12:34,811] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-29 19:12:34,878] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-29 19:12:34,906] {logging_mixin.py:112} INFO - [2021-01-29 19:12:34,893] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-29 19:12:34,907] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 19:12:34,953] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.368 seconds
[2021-01-29 20:59:57,988] {scheduler_job.py:154} INFO - Started process (PID=17720) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 20:59:58,028] {logging_mixin.py:112} INFO - [2021-01-29 20:59:58,028] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-29 20:59:58,030] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-29 20:59:58,030] {logging_mixin.py:112} INFO - [2021-01-29 20:59:58,030] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 20:59:58,034] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-29 20:59:58,044] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-29 20:59:58,046] {logging_mixin.py:112} INFO - [2021-01-29 20:59:58,045] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-29 20:59:58,047] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 20:59:58,057] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.069 seconds
[2021-01-29 23:13:55,399] {scheduler_job.py:154} INFO - Started process (PID=17798) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 23:13:55,537] {logging_mixin.py:112} INFO - [2021-01-29 23:13:55,536] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-29 23:13:55,543] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-29 23:13:55,544] {logging_mixin.py:112} INFO - [2021-01-29 23:13:55,544] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 23:13:55,560] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-29 23:13:55,583] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-29 23:13:55,592] {logging_mixin.py:112} INFO - [2021-01-29 23:13:55,587] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-29 23:13:55,593] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-29 23:13:55,631] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.231 seconds
[2021-01-30 02:26:29,680] {scheduler_job.py:154} INFO - Started process (PID=17899) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 02:26:29,732] {logging_mixin.py:112} INFO - [2021-01-30 02:26:29,732] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-30 02:26:29,734] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-30 02:26:29,734] {logging_mixin.py:112} INFO - [2021-01-30 02:26:29,734] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 02:26:29,740] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-30 02:26:29,750] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-30 02:26:29,754] {logging_mixin.py:112} INFO - [2021-01-30 02:26:29,752] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-30 02:26:29,754] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 02:26:29,769] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.089 seconds
[2021-01-30 04:15:24,336] {scheduler_job.py:154} INFO - Started process (PID=18002) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 04:15:24,378] {logging_mixin.py:112} INFO - [2021-01-30 04:15:24,377] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-30 04:15:24,380] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-30 04:15:24,380] {logging_mixin.py:112} INFO - [2021-01-30 04:15:24,380] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 04:15:24,384] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-30 04:15:24,393] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-30 04:15:24,396] {logging_mixin.py:112} INFO - [2021-01-30 04:15:24,394] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-30 04:15:24,396] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 04:15:24,407] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.071 seconds
[2021-01-30 07:51:41,428] {scheduler_job.py:154} INFO - Started process (PID=18092) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 07:51:41,467] {logging_mixin.py:112} INFO - [2021-01-30 07:51:41,467] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-30 07:51:41,469] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-30 07:51:41,469] {logging_mixin.py:112} INFO - [2021-01-30 07:51:41,469] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 07:51:41,474] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-30 07:51:41,481] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-30 07:51:41,483] {logging_mixin.py:112} INFO - [2021-01-30 07:51:41,482] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-30 07:51:41,484] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 07:51:41,496] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.068 seconds
[2021-01-30 09:42:59,632] {scheduler_job.py:154} INFO - Started process (PID=18265) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 09:42:59,673] {logging_mixin.py:112} INFO - [2021-01-30 09:42:59,673] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-30 09:42:59,675] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-30 09:42:59,676] {logging_mixin.py:112} INFO - [2021-01-30 09:42:59,675] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 09:42:59,684] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-30 09:42:59,697] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-30 09:42:59,707] {logging_mixin.py:112} INFO - [2021-01-30 09:42:59,699] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-30 09:42:59,708] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 09:42:59,719] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.086 seconds
[2021-01-30 09:44:11,355] {scheduler_job.py:154} INFO - Started process (PID=18327) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 09:44:11,393] {logging_mixin.py:112} INFO - [2021-01-30 09:44:11,393] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-30 09:44:11,395] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-30 09:44:11,395] {logging_mixin.py:112} INFO - [2021-01-30 09:44:11,395] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 09:44:11,399] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-30 09:44:11,406] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-30 09:44:11,408] {logging_mixin.py:112} INFO - [2021-01-30 09:44:11,407] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-30 09:44:11,409] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 09:44:11,421] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.066 seconds
[2021-01-30 10:53:32,288] {scheduler_job.py:154} INFO - Started process (PID=18423) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 10:53:32,327] {logging_mixin.py:112} INFO - [2021-01-30 10:53:32,326] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-30 10:53:32,328] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-30 10:53:32,328] {logging_mixin.py:112} INFO - [2021-01-30 10:53:32,328] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 10:53:32,333] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-30 10:53:32,340] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-30 10:53:32,342] {logging_mixin.py:112} INFO - [2021-01-30 10:53:32,341] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-30 10:53:32,343] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 10:53:32,354] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.066 seconds
[2021-01-30 10:54:44,987] {scheduler_job.py:154} INFO - Started process (PID=18489) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 10:54:45,026] {logging_mixin.py:112} INFO - [2021-01-30 10:54:45,026] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-30 10:54:45,027] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-30 10:54:45,028] {logging_mixin.py:112} INFO - [2021-01-30 10:54:45,028] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 10:54:45,032] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-30 10:54:45,039] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-30 10:54:45,041] {logging_mixin.py:112} INFO - [2021-01-30 10:54:45,040] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-30 10:54:45,042] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 10:54:45,054] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.067 seconds
[2021-01-30 11:03:34,308] {scheduler_job.py:154} INFO - Started process (PID=18582) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 11:03:34,349] {logging_mixin.py:112} INFO - [2021-01-30 11:03:34,348] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-30 11:03:34,350] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-30 11:03:34,350] {logging_mixin.py:112} INFO - [2021-01-30 11:03:34,350] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 11:03:34,360] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-30 11:03:34,370] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-30 11:03:34,375] {logging_mixin.py:112} INFO - [2021-01-30 11:03:34,371] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-30 11:03:34,375] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 11:03:34,387] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.079 seconds
[2021-01-30 11:52:27,424] {scheduler_job.py:154} INFO - Started process (PID=18653) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 11:52:27,467] {logging_mixin.py:112} INFO - [2021-01-30 11:52:27,467] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-30 11:52:27,469] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-30 11:52:27,470] {logging_mixin.py:112} INFO - [2021-01-30 11:52:27,470] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 11:52:27,477] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-30 11:52:27,486] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-30 11:52:27,490] {logging_mixin.py:112} INFO - [2021-01-30 11:52:27,487] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-30 11:52:27,491] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 11:52:27,502] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.078 seconds
[2021-01-30 13:40:26,212] {scheduler_job.py:154} INFO - Started process (PID=18749) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 13:40:26,252] {logging_mixin.py:112} INFO - [2021-01-30 13:40:26,252] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-30 13:40:26,254] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-30 13:40:26,254] {logging_mixin.py:112} INFO - [2021-01-30 13:40:26,254] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 13:40:26,258] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-30 13:40:26,268] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-30 13:40:26,271] {logging_mixin.py:112} INFO - [2021-01-30 13:40:26,270] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-30 13:40:26,271] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 13:40:26,293] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.081 seconds
[2021-01-30 13:57:34,937] {scheduler_job.py:154} INFO - Started process (PID=18835) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 13:57:34,977] {logging_mixin.py:112} INFO - [2021-01-30 13:57:34,977] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-30 13:57:34,979] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-30 13:57:34,979] {logging_mixin.py:112} INFO - [2021-01-30 13:57:34,979] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 13:57:34,983] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-30 13:57:34,992] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-30 13:57:34,995] {logging_mixin.py:112} INFO - [2021-01-30 13:57:34,994] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-30 13:57:34,995] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 13:57:35,006] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.069 seconds
[2021-01-30 14:11:13,763] {scheduler_job.py:154} INFO - Started process (PID=18930) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 14:11:13,804] {logging_mixin.py:112} INFO - [2021-01-30 14:11:13,802] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-30 14:11:13,805] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-30 14:11:13,805] {logging_mixin.py:112} INFO - [2021-01-30 14:11:13,805] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 14:11:13,810] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-30 14:11:13,818] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-30 14:11:13,821] {logging_mixin.py:112} INFO - [2021-01-30 14:11:13,819] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-30 14:11:13,821] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 14:11:13,832] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.069 seconds
[2021-01-30 14:23:18,916] {scheduler_job.py:154} INFO - Started process (PID=19010) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 14:23:18,956] {logging_mixin.py:112} INFO - [2021-01-30 14:23:18,955] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-30 14:23:18,957] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-30 14:23:18,957] {logging_mixin.py:112} INFO - [2021-01-30 14:23:18,957] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 14:23:18,962] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-30 14:23:18,980] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-30 14:23:18,983] {logging_mixin.py:112} INFO - [2021-01-30 14:23:18,981] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-30 14:23:18,983] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 14:23:18,994] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.078 seconds
[2021-01-30 14:33:11,535] {scheduler_job.py:154} INFO - Started process (PID=19091) to work on /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 14:33:11,574] {logging_mixin.py:112} INFO - [2021-01-30 14:33:11,573] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-30 14:33:11,575] {scheduler_job.py:1572} INFO - Processing file /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py for tasks to queue
[2021-01-30 14:33:11,575] {logging_mixin.py:112} INFO - [2021-01-30 14:33:11,575] {dagbag.py:417} INFO - Filling up the DagBag from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 14:33:11,580] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/utils/helpers.py:436: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  warnings.warn(
[2021-01-30 14:33:11,588] {logging_mixin.py:112} WARNING - /Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dag.py:1337: PendingDeprecationWarning: The requested task could not be added to the DAG with dag_id covid_warehouse_dag because a task with task_id Loadfact_open_metrics is already in the DAG. Starting in Airflow 2.0, trying to overwrite a task will raise an exception.
  warnings.warn(
[2021-01-30 14:33:11,591] {logging_mixin.py:112} INFO - [2021-01-30 14:33:11,589] {dagbag.py:259} ERROR - Failed to import: /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
Traceback (most recent call last):
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/site-packages/airflow/models/dagbag.py", line 256, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/Users/hiroakioshima/opt/anaconda3/envs/covid_airflow/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py", line 497, in <module>
    Load_healthcarefacs_redshift >> loaddim_healthcare
NameError: name 'Load_healthcarefacs_redshift' is not defined
[2021-01-30 14:33:11,591] {scheduler_job.py:1586} WARNING - No viable dags retrieved from /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py
[2021-01-30 14:33:11,602] {scheduler_job.py:162} INFO - Processing /Users/hiroakioshima/Desktop/airflow_covid/airflow/dags/covid_dag.py took 0.067 seconds
